apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: zaksoft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: auth-service:v6
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: zaksoft-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: zaksoft-secrets
              key: JWT_SECRET
        - name: REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: zaksoft-secrets
              key: REFRESH_SECRET
