apiVersion: v1
kind: Secret
metadata:
  name: zaksoft-secrets
  namespace: zaksoft
type: Opaque
stringData:
  JWT_SECRET: zaksoft_secret
  REFRESH_SECRET: zaksoft_refresh_secret
  DATABASE_URL: postgresql://zaksoft:zaksoft123@postgres:5432/zaksoft
  POSTGRES_PASSWORD: zaksoft123
  OPENAI_API_KEY: ta_cle
  STRIPE_SECRET_KEY: ta_cle
